// Bulk-import public-domain books from Project Gutenberg (via Gutendex) WITHOUT
// touching the existing catalogue or anyone's reading data. Appends only, skips
// anything we already have (by file URL and by title+author), and walks
// Gutendex newest-popularity-first so the best-known classics come in first.
//
//   npm run db:import            # add up to 500 new books
//   npm run db:import -- 1000    # add up to 1000 new books
//
// Files stream to the reader through our /api/book-file proxy (no hosting cost).
// Covers are generated by <BookCover> from genre/title, so a big catalogue looks
// uniform — we still store coverUrl/description/year for the detail page.
import { db, schema } from "@/db";
import type { NewBook } from "@/db/schema";

const TARGET = Number(process.argv[2] || 500); // how many NEW books to add
const GUTENDEX = "https://gutendex.com/books";
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

type GAuthor = { name: string; birth_year?: number | null; death_year?: number | null };
type GBook = {
  id: number;
  title: string;
  authors: GAuthor[];
  summaries?: string[];
  subjects?: string[];
  bookshelves?: string[];
  languages?: string[];
  copyright?: boolean | null;
  formats: Record<string, string>;
};

function fmtAuthor(name?: string): string {
  if (!name) return "Unknown";
  const parts = name.split(",").map((s) => s.trim());
  return parts.length === 2 && parts[1] ? `${parts[1]} ${parts[0]}` : name;
}
function pickGenre(b: GBook): string {
  const hay = [...(b.subjects || []), ...(b.bookshelves || [])].join(" | ").toLowerCase();
  if (/science fiction|fantasy/.test(hay)) return "sci";
  if (/poetry|poems/.test(hay)) return "poetry";
  if (/history|historical|war/.test(hay)) return "history";
  if (/philosophy|ethics|conduct of life/.test(hay)) return "self";
  if (/biography|autobiography|letters|essays|science|natural history/.test(hay)) return "nonfic";
  return "fiction";
}
function epubUrl(b: GBook): string | null {
  for (const [k, v] of Object.entries(b.formats || {})) if (k.startsWith("application/epub+zip")) return v;
  return null;
}
function coverUrl(b: GBook): string | null {
  for (const [k, v] of Object.entries(b.formats || {})) if (k.startsWith("image/")) return v;
  return null;
}
const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

async function fetchJson<T>(url: string, tries = 4): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0 ReadLeague-import" } });
      if (r.ok) return (await r.json()) as T;
      lastErr = new Error(`HTTP ${r.status}`);
    } catch (e) { lastErr = e; }
    await sleep(700 * 2 ** i);
  }
  throw lastErr;
}

async function main() {
  console.log(`Importing up to ${TARGET} new public-domain books (non-destructive)…`);

  // Build dedupe sets from what's already in the library.
  const existing = await db.select({ fileUrl: schema.books.fileUrl, title: schema.books.title, author: schema.books.author }).from(schema.books);
  const haveUrl = new Set(existing.map((e) => e.fileUrl).filter(Boolean) as string[]);
  const haveKey = new Set(existing.map((e) => `${norm(e.title)}|${norm(e.author)}`));
  console.log(`  library already has ${existing.length} books`);

  let added = 0;
  let pageUrl: string | null = `${GUTENDEX}?languages=en&mime_type=application/epub`;
  try {
    while (pageUrl && added < TARGET) {
      const data: { results: GBook[]; next: string | null } = await fetchJson(pageUrl);
      const batch: NewBook[] = [];
      for (const b of data.results) {
        if (b.copyright === true) continue; // public-domain only
        const url = epubUrl(b);
        if (!url || haveUrl.has(url)) continue;
        const author = fmtAuthor(b.authors?.[0]?.name);
        const key = `${norm(b.title)}|${norm(author)}`;
        if (haveKey.has(key)) continue;
        haveUrl.add(url);
        haveKey.add(key);
        const death = b.authors?.[0]?.death_year ?? null;
        batch.push({
          title: (b.title || "Untitled").slice(0, 150),
          author,
          genre: pickGenre(b),
          format: "EPUB",
          fileUrl: url,
          coverUrl: coverUrl(b),
          description: (b.summaries?.[0] || "").slice(0, 1200) || null,
          year: death && death > 0 && death < 2100 ? death : null, // rough era marker
          status: "approved",
          lockType: "open",
        });
        if (added + batch.length >= TARGET) break;
      }
      if (batch.length) { await db.insert(schema.books).values(batch); added += batch.length; }
      pageUrl = data.next;
      process.stdout.write(`\r  added ${added}/${TARGET}…   `);
      await sleep(350); // be polite to Gutendex
    }
    console.log("");
  } catch (e) {
    console.log(`\n  ⚠ stopped early (${String(e)}) — added ${added} before the error.`);
  }

  const totalNow = (await db.select({ id: schema.books.id }).from(schema.books)).length;
  console.log(`  ✓ added ${added} new books — library is now ${totalNow} books`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
